### ISSUE TITLE
Support data volume containers

### ISSUE THREAD

**Issue by codders** [advancedtelematic/docker-launcher#11]
Would be nice to be able to use data volumes in Docker Launcher configs:

https://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container

Desired syntax:
```yaml
  - name: datastore
    repo: debian:jessie
    volume: /var/lib/mysql
    command: /bin/true

  - name: mysql
    repo: advancedtelematic/mariadb
    volumes-from: datastore
    ports:
      - 3306
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_user_password }}"
      MYSQL_DATABASES: "{{ db_resolver_name }} {{ db_core_name }} {{ db_core_name }}_test {{ db_resolver_name }}_test"
```
